BEGIN TRANSACTION;
CREATE DATABASE CustomersDB;
COMMIT TRANSACTION;

BEGIN TRANSACTION;
CREATE TABLE CUSTOMER(
Idcustomer INT PRIMARY KEY IDENTITY(1,1),
Customername  VARCHAR(50) NOT NULL,
);
COMMIT TRANSACTION;

BEGIN TRANSACTION;
INSERT INTO CUSTOMER(Customername) 
VALUES ('JulienZ');
INSERT INTO CUSTOMER(Customername)
VALUES ('PatriciaZ'); 
COMMIT TRANSACTION;


BEGIN TRANSACTION;
UPDATE CUSTOMER 
SET Customername = TRIM('Z' FROM Customername)
WHERE RIGHT(Customername, 1) = 'Z';
COMMIT TRANSACTION; 